AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'bundler/**'
    - 'vendor/**'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'